# from JSON to pandas/from pandas to JSON

In [86]:
import json 
from pprint import pprint 
import pandas as pd

### **ИЗ JSON В PANDAS**

In [87]:
with open('data/recipes.json') as f: 
    # Загружаем содержимое открытого файла в переменную recipes
    recipes = json.load(f) 
# Создаём объект DataFrame из списка recipes
df = pd.DataFrame(recipes) 
# Выводим на экран первые строки полученного DataFrame
display(df.head())

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

#### **или**

In [88]:
# Создаём объект DataFrame, загружая содержимое файла recipes.json
df = pd.read_json('data/recipes.json') 
# Выводим на экран первые строки полученного DataFrame
display(df.head())

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

### **Прообразование столбца ingredients в one hot encoding**

In [89]:
all_ingredients = list(df['ingredients'].explode().unique())
# Определяем имя функции и передаваемые аргументы    
def contains(ingredient_list): 
    # Если ингредиент есть в текущем блюде,
    if ingredient_name in ingredient_list:   
        # возвращаем значение 1
        return 1 
    # Если ингредиента нет в текущем блюде,
    else: 
        # возвращаем значение 0
        return 0
# Последовательно перебираем ингредиенты в реестре all_ingredients
for ingredient_name in all_ingredients: 
    # В DataFrame cоздаем столбец с именем текущего ингредиента 
    # и заполняем его единицами и нулями,
    # используя ранее созданную функцию contains
    df[ingredient_name] = df['ingredients'].apply(contains)
# Заменяем список ингредиентов в рецепте на их количество 
df['ingredients'] = df['ingredients'].apply(len) 
# Выводим содержимое полученного DataFrame на экран
display(df)

C:\Users\Romanov Roman\AppData\Local\Temp\ipykernel_6400\2161362430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)

,id,cuisine,ingredients,romaine lettuce,black olives,grape tomatoes,garlic,pepper,purple onion,seasoning,...,string beans,egg roll wraps,steamed rice,penne,Crystal Farms Butter,Crystal Farms Shredded Gouda Cheese,mint,berries,figs,sprinkles
0,10259,greek,9,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,12,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22213,indian,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1121,chinese,9,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
496,18376,italian,8,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
497,17815,italian,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,32878,southern_us,19,0,0,0,1,0,0,0,...,0,0,0,0,1,1,0,0,0,0
499,24410,british,17,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1

### **СОХРАНЯЕМ DATAFRAME В CSV-ФАЙЛЕ**

In [90]:
df.to_csv('data/recipes.csv', index = False)

### **ИЗ PANDAS В JSON**

In [91]:
# Создаём DataFrame, читаем данные из файла в переменную df
df = pd.read_csv('data/recipes.csv')
# создаем список из уникальных id блюд
ids = list(df['id'].unique())
# создаем список из всех ингридиентов блюд 
ingredients = list(df.columns)[3::]
# инициализируем функцию для создания спска ингридиентов для блюда
def make_list(row):
    return [ingredient for ingredient in ingredients if row[ingredient].any() > 0]
# Создаём пустой список для хранения итоговой структуры
new_recipes = [] 
# Организуем цикл с параметром current_id
for current_id in ids: 
    # Получаем значение соответствующей кухни, применив фильтр по текущему значению параметра цикла к DataFrame;
    cuisine = df[df['id'] == current_id]['cuisine'].iloc[0] 
    # Получаем перечень ингредиентов, входящих в состав текущего блюда
    current_ingredients = make_list(df[df['id'] == current_id]) 
    # Создаём текущий словарь
    current_recipe = {'cuisine': cuisine, 'id': int(current_id), 'ingredients': current_ingredients} 
    # Добавляем созданный словарь к списку
    new_recipes.append(current_recipe)

### **СОХРАНЯЕМ DATAFRAME В JSON-ФАЙЛЕ**

In [92]:
# Функция dumps() модуля json сериализирует объект Python в строку формата JSON. 
new_recipes = json.dumps(new_recipes) 
# Откроем файл new_recipes.json для записи
with open("data/new_recipes.json", "w") as write_file: 
    # Записываем содержимое подготовленные данные в файл
    write_file.write(new_recipes)