# **working with excel-files/работа с файлами excel**

### **read_excel()** 

Для чтения файла предварительно потребуется установить библиотеку **openpyxl** через команду **pip install openpyxl**.

In [1]:
import pandas as pd

In [2]:
grades = pd.read_excel('data/grades.xlsx')
display(grades.head())

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8

Считывание данных из файла EXCEL по ссылке

In [4]:
data = pd.read_excel('https://github.com/asaydn/test/raw/master/january.xlsx', skiprows=3)
display(data)

      Location  Oranges  Apples  Bananas  Blueberries  Total
0      Toronto     7651    4422     8580         3679  24332
1  Los Angeles      273    2998     9890         7293  20454
2      Atlanta     3758    6752     4599         4149  19258
3     New York     4019    8796     8486         9188  30489

### **Основные параметры метода read_excel()**
* **io** — первый параметр, в который мы передаём адрес файла, который хотим прочитать. Кроме адреса на диске, можно передавать адрес в интернете.
* **sheet_name** —  ссылка на лист в Excel-файле (возможные значения данного параметра: 0 — значение по умолчанию, загружается первый лист; 'Sheet1' — можно передать название листа; обычно листы называются 'SheetX', где X — номер листа, но могут использоваться и другие названия; [0, 1, 'Sheet3'] — список, содержащий номера или названия листов; в таком случае Pandas вернёт словарь, в котором ключами будут номера или названия листов, а значениями — их содержимое в виде DataFrame; None — если передать такое значение, то pandas прочитает все листы и вернёт их в виде словаря, как в предыдущем пункте).
* **na_values** — список значений, которые будут считаться пропусками ( ‘’, ‘#N/A’, ‘ N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’).

In [7]:
grades = pd.read_excel('data/grades.xlsx', sheet_name='ML')
display(grades.head())
grades_maths = pd.read_excel('data/grades.xlsx', sheet_name='Maths')
display(grades_maths.head())

   Student ID Student name  Grade
0           1          Аня      7
1           2         Катя      5
2           3         Маша      9
3           4         Миша      8
4           5         Женя      9

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8

### **to_excel()**

In [10]:
# Сохраняем данные из DataFrame grades в файл grades_new.xlsx в папке data
grades.to_excel('data/grades_new.xlsx')

In [11]:
# Сохраняем данные из DataFrame grades в файл grades_new.xlsx (на листе 'Example') в папке data
grades.to_excel('data/grades_new_1.xlsx', sheet_name='Example', index=False)

### **Биоблиотеки для работы с excel**

* openpyxl — рекомендуемый пакет для чтения и записи файлов Excel 2010+ (например, xlsx);
* xlsxwriter — альтернативный пакет для записи данных, информации о форматировании и, в частности, диаграмм в формате Excel 2010+ (например, xlsx);
* pyxlsb — пакет позволяет читать файлы Excel в xlsb-формате;
* pylightxl — пакет позволяет читать xlsx- и xlsm-файлы и записывать xlsx-файлы;
* xlrd — пакет предназначен для чтения данных и информации о форматировании из старых файлов Excel (например, xls);
* xlwt — пакет предназначен для записи данных и информации о форматировании в старые файлы Excel (например, xls).

In [15]:
ratings = pd.read_excel(io='data/ratings_movies.xlsx', sheet_name='ratings')
display(ratings.head())
movies = pd.read_excel(io='data/ratings_movies.xlsx', sheet_name='movies')
display(movies.head())

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [24]:
ratings_of_movies = pd.merge(left=ratings, 
                             right=movies, 
                             on='movieId', 
                             how='left')
ratings_of_movies.to_excel('data/ratings_of_movies.xlsx', sheet_name='JOINED', index=False)